In [6]:
import itertools
import numpy as np
import time

# tarc = [1,2,3,4,1]
tarc = [1,2,1]
for lnum in range(1, len(tarc) + 1):
    # ret_list = list(itertools.combinations(tarc,lnum))
    # ret_list = list(itertools.combinations_with_replacement(tarc,lnum))
    # ret_list = list(itertools.permutations(tarc,lnum))
    ret_list = list(itertools.permutations(tarc,len(tarc)))
    print(ret_list)
    print(set(ret_list))
# print(ret_list)

[(1, 2, 1), (1, 1, 2), (2, 1, 1), (2, 1, 1), (1, 1, 2), (1, 2, 1)]
{(1, 2, 1), (2, 1, 1), (1, 1, 2)}
[(1, 2, 1), (1, 1, 2), (2, 1, 1), (2, 1, 1), (1, 1, 2), (1, 2, 1)]
{(1, 2, 1), (2, 1, 1), (1, 1, 2)}
[(1, 2, 1), (1, 1, 2), (2, 1, 1), (2, 1, 1), (1, 1, 2), (1, 2, 1)]
{(1, 2, 1), (2, 1, 1), (1, 1, 2)}


In [ ]:
for NUM in range(3, 32):
    total_list = list(range(NUM))
    ret = []
    stime = time.time()
    for n in range(1, NUM+1):
        ret += list(itertools.combinations(total_list,n))
    etime = time.time()
    print(f'{NUM}, time:{etime - stime}')
    print(ret)
# print(ret)

28, time:36.50596523284912


ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\49467\AppData\Local\Temp\ipykernel_30240\2973310809.py", line 5, in <module>
    for n in range(1, NUM+1):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2077, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\ProgramData\Anaconda3\lib\s

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



ERROR! Session/line number was not unique in database. History logging moved to new session 139
[(0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]
3, time:0.0
[(0,), (1,), (2,), (3,), (0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3), (0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3), (0, 1, 2, 3)]
4, time:0.0
[(0,), (1,), (2,), (3,), (4,), (0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4), (0, 1, 2), (0, 1, 3), (0, 1, 4), (0, 2, 3), (0, 2, 4), (0, 3, 4), (1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4), (0, 1, 2, 3), (0, 1, 2, 4), (0, 1, 3, 4), (0, 2, 3, 4), (1, 2, 3, 4), (0, 1, 2, 3, 4)]
5, time:0.0
[(0,), (1,), (2,), (3,), (4,), (5,), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5), (0, 1, 2), (0, 1, 3), (0, 1, 4), (0, 1, 5), (0, 2, 3), (0, 2, 4), (0, 2, 5), (0, 3, 4), (0, 3, 5), (0, 4, 5), (1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (1, 4, 5), (2, 3, 4), (2, 3, 5), (2, 4, 5), (3, 4, 5)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.


KeyboardInterrupt



In [12]:
a = np.array([[1, 2, 3], [4 ,5 ,6], [7 ,8 ,9]])
print(a)
print(np.sum(a[0]))
print(np.sum(a[1]))
print(np.sum(a[2]))
print(np.sum(a.T[0]))
print(np.sum(a.T[1]))
print(np.sum(a.T[2]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
15
24
12
15
18


In [3]:
test_list = [0,1,2,3,4,5,6]
ret_list = []
for lnum in range(len(test_list)):
    ret_list += list(itertools.combinations(test_list,lnum))
    print(list(itertools.combinations(test_list,lnum)))
print(ret_list)

[()]
[(0,), (1,), (2,), (3,), (4,), (5,), (6,)]
[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 3), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6), (4, 5), (4, 6), (5, 6)]
[(0, 1, 2), (0, 1, 3), (0, 1, 4), (0, 1, 5), (0, 1, 6), (0, 2, 3), (0, 2, 4), (0, 2, 5), (0, 2, 6), (0, 3, 4), (0, 3, 5), (0, 3, 6), (0, 4, 5), (0, 4, 6), (0, 5, 6), (1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 2, 6), (1, 3, 4), (1, 3, 5), (1, 3, 6), (1, 4, 5), (1, 4, 6), (1, 5, 6), (2, 3, 4), (2, 3, 5), (2, 3, 6), (2, 4, 5), (2, 4, 6), (2, 5, 6), (3, 4, 5), (3, 4, 6), (3, 5, 6), (4, 5, 6)]
[(0, 1, 2, 3), (0, 1, 2, 4), (0, 1, 2, 5), (0, 1, 2, 6), (0, 1, 3, 4), (0, 1, 3, 5), (0, 1, 3, 6), (0, 1, 4, 5), (0, 1, 4, 6), (0, 1, 5, 6), (0, 2, 3, 4), (0, 2, 3, 5), (0, 2, 3, 6), (0, 2, 4, 5), (0, 2, 4, 6), (0, 2, 5, 6), (0, 3, 4, 5), (0, 3, 4, 6), (0, 3, 5, 6), (0, 4, 5, 6), (1, 2, 3, 4), (1, 2, 3, 5), (1, 2, 3, 6), (1, 2, 4, 5), (1, 2, 4, 6), (1, 2, 5, 6), (1, 3, 4, 5), (1, 3, 4, 6), (1, 

In [6]:
stime = time.time()
for _ in range(1):
    time.sleep(1)
etime = time.time()
print(etime - stime)

1.0100200176239014


In [22]:
import numpy as np

ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# printing initial array
print("initial_array : ", str(ini_array))

# Array to be added as column
column_to_be_added = np.array([[1], [2], [3]])

# Adding column to array using append() method
arr = np.append(ini_array, column_to_be_added, axis=2)

# printing result
print ("resultant array", str(arr))

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]


AxisError: axis 2 is out of bounds for array of dimension 2

In [23]:
z = np.array([[1, 2], [3, 4]])
print(z.sum(axis=0))  # [4 6]
print(z.sum(axis=1))  # [3 7]

[4 6]
[3 7]


In [36]:
# 创建一个二维数组
a = np.array([[1, 2, 3], [4, 5,6], [7, 8, 9]])
# 创建一个新的一维数组
b = np.array([10, 11, 12])
# 在二维数组中插入一行
c1 = np.insert(a, a.shape[0], b, axis=0)
c2 = np.insert(a, a.shape[1], b, axis=1)
print(c1)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
